// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqOF5qmUFKwxS0oJk-nOwNc4inkTnYyVw',
    appId: '1:596295902068:web:c2cb49417e5a59ca598221',
    messagingSenderId: '596295902068',
    projectId: 'login-ec84e',
    authDomain: 'login-ec84e.firebaseapp.com',
    storageBucket: 'login-ec84e.appspot.com',
    measurementId: 'G-HTVH51XV5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4X5D00Y_zm0913qTMIft1f3vDQFHtQkE',
    appId: '1:596295902068:android:33ad9c5cfa7235bc598221',
    messagingSenderId: '596295902068',
    projectId: 'login-ec84e',
    storageBucket: 'login-ec84e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBOL3byRi_m53X8LSqvgRpvckjFxfvNU',
    appId: '1:596295902068:ios:cdbef682a78afc1d598221',
    messagingSenderId: '596295902068',
    projectId: 'login-ec84e',
    storageBucket: 'login-ec84e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeBOL3byRi_m53X8LSqvgRpvckjFxfvNU',
    appId: '1:596295902068:ios:cb3a40e9df564ec9598221',
    messagingSenderId: '596295902068',
    projectId: 'login-ec84e',
    storageBucket: 'login-ec84e.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
